name: Metrics
on:
  # 毎日日本時間の午前9時（UTC 0時）に自動更新
  schedule: [{cron: "0 0 * * *"}]
  # 手動でいつでも更新できるようにするボタンを有効化
  workflow_dispatch:
  # READMEを編集して保存した時にも更新が走るようにする
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: wakinoza
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo

          plugin_languages: yes
          plugin_languages_details: percentage 
          
          config_order: base.header, isocalendar, languages
