name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: wakinoza
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo

          plugin_languages: yes
          plugin_languages_details: percentage
          
          # スキル設定
          plugin_skills: yes
          plugin_skills_sections: languages, tools
          plugin_skills_languages: java, python, html, css, mysql
          plugin_skills_tools: git, github, vscode, eclipse, idea, notion, docker
          plugin_skills_limit: 20

          config_order: base.header, languages, skills
